[package]
name = "app-forge-kit-grpc-common"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Application forge kit gRPC common"
repository = { workspace = true }

[features]
builder = [
    "dep:tonic-prost-build"
]

macros = [
    "dep:tonic"
]

[dependencies.tonic]
workspace = true
features = [
    "codegen"
]
optional = true

[dependencies.tonic-prost-build]
workspace = true
optional = true
